version: '3.8'
networks:
  mynetwork:

services:
  web:
    networks:
      - mynetwork
    build: .
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 ecomproject.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  db:
    networks:
      - mynetwork
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:6
    restart: always
    command: redis-server --save "" --appendonly no --maxmemory 128mb --maxmemory-policy allkeys-lru   
    volumes:
      - redis_data:/data

  celery:
    build: .
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    command: celery -A ecomproject worker --loglevel=info
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    env_file:
      - .env
    command: celery -A ecomproject beat --loglevel=info
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  redis_data: