# Generated by Django 5.2.1 on 2025-05-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_category_title_alter_product_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="user",
        ),
        migrations.RemoveField(
            model_name="cartorder",
            name="user",
        ),
        migrations.RemoveField(
            model_name="cartorderitems",
            name="order",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
        migrations.RemoveField(
            model_name="product",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="productimages",
            name="product",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="user",
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="user",
        ),
        migrations.RemoveField(
            model_name="contactus",
            name="id",
        ),
        migrations.AddField(
            model_name="contactus",
            name="IsActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contactus",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="contactus",
            name="pid",
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="contactus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="CartOrder",
        ),
        migrations.DeleteModel(
            name="CartOrderItems",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="ProductImages",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductReview",
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
