# Generated by Django 5.2.1 on 2025-05-22 15:56

import shortuuid.django_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "pid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("IsActive", models.BooleanField(default=True)),
                (
                    "cid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=30,
                        prefix="cat",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="Category Name", max_length=100)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="post",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="post",
            name="date_updated",
        ),
        migrations.AddField(
            model_name="comment",
            name="IsActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="pid",
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="IsActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="pid",
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories", to="blog.postcategory"
            ),
        ),
    ]
