# Generated by Django 5.2.1 on 2025-05-22 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_postcategory_delete_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="id",
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
