# Generated by Django 5.2.1 on 2025-05-22 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "pid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("IsActive", models.BooleanField(default=True)),
                (
                    "orderStatus",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shipping_out", "Shipping Out"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("paid", "Paid"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash_on_delivery", "Cash on Delivery"),
                        ],
                        default="credit_card",
                        max_length=30,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Delivery"),
                            ("express", "Express Delivery"),
                            ("pickup", "Store Pickup"),
                        ],
                        default="standard",
                        max_length=30,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
                ),
                ("isPaid", models.BooleanField(default=False)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "pid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("IsActive", models.BooleanField(default=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Order Items",
            },
        ),
    ]
