# Generated by Django 5.2.1 on 2025-05-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.product"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="orderItems",
            field=models.ManyToManyField(
                through="order.OrderItem", to="product.product"
            ),
        ),
    ]
